// Colors
#macro UI_BG_COLOR #17172D
#macro UI_TEXT_COLOR #FFFFDF
#macro UI_HIGHLIGHT_COLOR #E9475F
#macro UI_ACCENT_COLOR #0F335F
#macro UI_SUCCESS_COLOR #4FCDA3

// Layout
#macro UI_TITLE_SIZE 1
#macro UI_TEXT_SIZE 0.5

#macro UI_HEADER_HEIGHT 4
#macro UI_FOOTER_HEIGHT 96
#macro UI_FOOTER_TEXT_Y 48

#macro UI_Y_TITLE 96
#macro UI_Y_SEPARATOR 192
#macro UI_Y_CONTENT_START 256

#macro UI_SEPARATOR_WIDTH 800
#macro UI_SEPARATOR_HEIGHT 4

#macro UI_MENU_HIGHLIGHT_WIDTH 800
#macro UI_MENU_HIGHLIGHT_PADDING 32

#macro UI_RESULTS_BOX_WIDTH 1280
#macro UI_RESULTS_BOX_HEIGHT 400

#macro UI_LINE_HEIGHT 64
#macro UI_SPACING 64